@host=http://localhost:8080

POST {{host}}/auth/login
Content-Type: application/json

{
    "username": "myuser",
    "password": "mypass"
}
###
POST {{host}}/auth/register
Content-Type: application/json

{
    "username": "myuser",
    "password": "mypass"
}
###
POST {{host}}/auth/refresh-login
Content-Type: application/json

{
    "refresh_token": "refreshToken"
}