@host=http://localhost:8080
@token=

POST {{host}}/complaint/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "",
    "last_name": "",
    "phone": "+5511987651234",
    "description": "Any description",
    "category": 1,
    "severity": 3
}