@host=http://localhost:8080
@token=

###
POST {{host}}/complaint/phone/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "John",
    "last_name": "Doe",
    "phone": "+55 9123-4567",
    "description": "Any description",
    "category": 1,
    "severity": 3
}

###
POST {{host}}/complaint/email/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "first_name": "Mary",
    "last_name": "Doe",
    "email": "mytest@gmail.com",
    "description": "Any description",
    "category": 2,
    "severity": 3
}

###
GET {{host}}/complaint/find-by-phone/+55 9123-4567?token={{token}}

###
GET {{host}}/complaint/find-by-email/mytest@gmail.com?token={{token}}

###
@contactId=
@complaintId=
DELETE  {{host}}/complaint/{{contactId}}/{{complaintId}}
Authorization: Bearer {{token}}
