@host=http://localhost:8080
@token=

###
POST {{host}}/contact/complaint/phone
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "John",
    "lastName": "Doe",
    "phone": "+55 9123-4567",
    "description": "Any description",
    "complaintCategory": "SCAM",
    "complaintSeverity": "ALERT"
}

###
POST {{host}}/contact/complaint/email
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "Mary",
    "lastName": "Doe",
    "email": "mytest@gmail.com",
    "description": "Any description",
    "complaintCategory": "SPAM",
    "complaintSeverity": "NOTICE"
}

###
GET {{host}}/contact/complaint/find-by-phone/+55 9123-4567?token={{token}}

###
GET {{host}}/contact/complaint/find-by-email/mytest@gmail.com?token={{token}}

###
@contactId=
@complaintId=
DELETE  {{host}}/contact/{{contactId}}/complaint/{{complaintId}}
Authorization: Bearer {{token}}
